service: AuctionService

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  
functions:
  CreateAuction:
    handler: src/handlers/CreateAuction.handler
    events:
      - http:
          method: POST
          path: /auction

# disable linting
custom:
  bundle:
    linting: false
